### ISSUE TITLE
Errors while making

### ISSUE THREAD

**Issue by j0sete** [ULE-Alliance/hanfun#36]
I download the code and follow these instruction: http://ule-alliance.github.io/hanfun/index.html to set up the project, but when doing make command, I got errors:

```
/home/jrodriguez/Downloads/hanfun-master/src/attributes.cpp: In function ‘HF::Attributes::IAttribute* HF::Core::create_attribute(HF::Core::DeviceInformation::Server*, uint8_t)’:
/home/jrodriguez/Downloads/hanfun-master/src/attributes.cpp:960:67: error: ‘application_version’ is not a member of ‘HF::Core::DeviceInformation::Server’
     auto getter = (const std::string (Server::*)(void)) & Server::application_version;
^
/home/jrodriguez/Downloads/hanfun-master/src/attributes.cpp:977:67: error: ‘hardware_version’ is not a member of ‘HF::Core::DeviceInformation::Server’
auto getter = (const std::string (Server::*)(void)) & Server::hardware_version;
 ^
/home/jrodriguez/Downloads/hanfun-master/src/attributes.cpp:1004:67: error: ‘manufacturer_name’ is not a member of ‘HF::Core::DeviceInformation::Server’
auto getter = (const std::string (Server::*)(void)) & Server::manufacturer_name;
^
make[2]: *** [src/CMakeFiles/hanfun.dir/attributes.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/hanfun.dir/all] Error 2
make: *** [all] Error 2
```

How can I solved this, I'm don't have many experience on c++ and i don't know how to fix it.

**Comment by bithium** [comment]
Hello José,

sorry about that. We had a bug in the preprocessor defines usage. We have fixed it.

Please pull the master branch again and try it again.

**Comment by j0sete** [comment]
Hello bithium,

The new release solved my problem, I was able to make the project now, but i find some new issues:
- When make the examples, they failed with a core dumped exeption while doing an assert _(output error [1] at the end)_ , if I comment the line 678 on file /src/protocol.cpp (basically the assert) it works fine on example 1, 2 and 3, didn't test the others.
- When making the test I passed the option `-DHAN-FUN_BUILD_TESTS=ON` to `cmake` and the cmake response ignoring it because there is no variable with that name _(output error [2] at the end)_ , but if i pass the option `-DHF_BUILD_TESTS=ON` it response with errors, so I was unable to do that part:

```
CMake Error at tests/CMakeLists.txt:25 (add_subdirectory):
  The source directory

    /home/jrodriguez/Documents/hanfun-1.4.1/tests/cpputest

  does not contain a CMakeLists.txt file.


CMake Error at tests/CMakeLists.txt:27 (find_package):
  Could not find a package configuration file provided by "CppUTest" with any
  of the following names:

    CppUTestConfig.cmake
    cpputest-config.cmake

  Add the installation prefix of "CppUTest" to CMAKE_PREFIX_PATH or set
  "CppUTest_DIR" to a directory containing one of the above files.  If
  "CppUTest" provides a separate development package or SDK, be sure it has
  been installed.


-- Configuring incomplete, errors occurred!

```
- I was unable to test the three terminals examples, after doing cmake and make, on apps/ directory there is no node or base executable. There aren't implement on the CMakeList ???

Thanks for your work!

Errors output:

[1]

```
root@jrodriguez:/home/jrodriguez/Documents/hanfun-1.4.1/build# apps/example_01 
[INFO ] Use case : Basic registration
[INFO ] Create the node instances ...
[INFO ] Create the base instance ...
[INFO ] Create transport instance
[INFO ] Network setup ...
[INFO ] Registering node1 ... 
example_01: /home/jrodriguez/Documents/ULE/hanfun-1.4.1/src/protocol.cpp:678: bool HF::Protocol::Filters::ResponseRequired::operator()(const HF::Protocol::Packet&): Assertion `address != Protocol::BROADCAST_ADDR' failed.
Aborted (core dumped)
```

[2]

```
[...]
CMake Warning:
  Manually-specified variables were not used by the project:

    HAN-FUN_BUILD_TESTS
```

**Comment by bithium** [comment]
Hello José,

it took me some time, however I have fixed the issues you mention.

I have updated the README to indicate the correct configuration values 
for building the unit tests and the applications. I also fixed the 
example applications, they should be working now.

Best regards,

_Filipe Alves_
Senior Developer

---

_Bithium ® S.A._ • Av. Miguel Bombarda, 129 R/C • 1050-154 Lisboa • Portugal
_Phone_ +351 21 3304224 • _Fax_ +351 21 3304225 • _Web_ 
http://www.bithium.com • _Skype_ /bithium/

---

**Comment by j0sete** [comment]
Hello Bithium,

Now I can test the hf_base & hf_node consoles, but when I try to register a node to the base it failed and message me this:

```
> [INFO ] Connected !
r

hf_node: /home/jrodriguez/Downloads/hanfun-1.4.2/src/protocol.cpp:682: bool HF::Protocol::Filters::ResponseRequired::operator()(const HF::Protocol::Packet&): Assertion `address != Protocol::BROADCAST_ADDR' failed.
Aborted (core dumped)
```

What did I do bad ? I followed the steps on README.MD:
1. Open two terminals and executed `$ hf_base` followed by `$ hf_node 1`
2. On hf_base terminal write the command: `> r 1 1`
3. On hf_node terminal wrote: `> r`

After the error message on hf_base terminal:

```
> [INFO ] Connection accepted !
r 1 1
[INFO ] Next Registration will have address : 1
> [INFO ] Saving registration entries ...
[INFO ] Saving binding entries ...
[INFO ] Application configuration saved !

lr
HAN-FUN  Registered Devices (1):
-     1 | uri: hf://node.example.com/1
```

So, the base registered but the node fail.

Thanks for all your work!

José Manuel Rodríguez

**Comment by bithium** [comment]
Hello José,

there was an issue with the code that ensures that required responses 
are send when a device is not yet registered. This should be fixed now.

Please try it again.

Best regards,

_Filipe Alves_
Senior Developer

---

_Bithium ® S.A._ • Av. Miguel Bombarda, 129 R/C • 1050-154 Lisboa • Portugal
_Phone_ +351 21 3304224 • _Fax_ +351 21 3304225 • _Web_ 
http://www.bithium.com • _Skype_ /bithium/

---

**Comment by j0sete** [comment]
Hello Bithium,

Thank you very much for your job, all works fine.

Regards,

**José Manuel Rodríguez Montes**
Junior Developer
<3wisecookies/>
